[project]
name = "scons-conan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "conan>=2.25.2",
    "scons>=4.10.1",
]
